### ISSUE TITLE
Please publish your package peerlibrary:pdf.js for Windows

### ISSUE THREAD

**Issue by avital** [peerlibrary/meteor-pdf.js#17]
Hi!

This package has binary dependencies, and we wanted to give you a heads up that Meteor 1.1, with support for Windows will be released in a few days.

Now is the time to publish your package for Windows!

It should be very straightforward -- we've added new build machines that run Windows that you can access with the `meteor admin get-machine` command. This is the same as you've done before for the other architectures we support.

For complete directions on how to publish your package for Windows, visit https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview

On behalf of the Meteor team,
@stubailo, @Slava and @avital.

P.S. This is an automated message based on our database of package authors.

**Comment by avital** [comment]
(Thanks @mitar for making me create automated tickets in addition to sending emails! :) )

**Comment by mitar** [comment]
I want to see this script/program! :-)

**Comment by wimco** [comment]
I would also like to run it on Windows!  Please?

**Comment by mitar** [comment]
I do not have Windows. If somebody tries first to compile it on Windows and sees if everything works, I can then publish it. But I believe there might be issues with all dependencies needed (Cairo, etc.).

**Comment by wimco** [comment]
According to the original post above and the link therein, it does not seem like you need a Windows machine, but that releasing a new version will automatically build it for Windows too.  Unless I misunderstand.
I've never done this before so am not too sure what the process is...

**Comment by mitar** [comment]
Yea, but that is assuming that it will just work. But this package uses binary dependencies (this is why it has to be compiled in the first place for Windows) and somebody should look into how to use those binary dependencies on Windows.

**Comment by wimco** [comment]
Understood, I'll try running it on Linux for now.
When deploying to XYZ.meteor.com, it also fails :( 

```
WARNING Error: libgif.so.4: cannot open shared object file: No
such file or directory
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/meteor/containers/4ed9c2ef-2255-ae0b-76e7-2713fed3ab67/bundle/programs/server/npm/peerlibrary_pdf.js/node_modules/canvas/lib/bindings.js:2:18)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```

**Comment by ncrmro** [comment]
Wen't ahead and moved this comment to an issue.
