### ISSUE TITLE
Getting libgif missing errors vagrant/ubuntu and home-brew.

### ISSUE THREAD

**Issue by ncrmro** [peerlibrary/meteor-pdf.js#19]
I'm getting the same issue as wimco on vagrant ubuntu and home-brew os x I've used the following commands

OS X 

```
=> Exited with code: 8
W20151208-14:12:25.689(-6)? (STDERR)          
W20151208-14:12:25.689(-6)? (STDERR) /Users/ncrmro/.meteor/packages/meteor-tool/.1.1.10.102f3ag++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151208-14:12:25.689(-6)? (STDERR)                                            throw(ex);
W20151208-14:12:25.689(-6)? (STDERR)                                                  ^
W20151208-14:12:25.751(-6)? (STDERR) Error: dlopen(/Users/ncrmro/.meteor/packages/peerlibrary_pdf.js/.1.0.791_4.d8ohlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/canvas/build/Release/canvas.node, 1): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
W20151208-14:12:25.751(-6)? (STDERR)   Referenced from: /Users/ncrmro/.meteor/packages/peerlibrary_pdf.js/.1.0.791_4.d8ohlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/canvas/build/Release/canvas.node
W20151208-14:12:25.751(-6)? (STDERR)   Reason: image not found
W20151208-14:12:25.751(-6)? (STDERR)     at Module.load (module.js:356:32)
W20151208-14:12:25.752(-6)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151208-14:12:25.752(-6)? (STDERR)     at Module.require (module.js:364:17)
W20151208-14:12:25.752(-6)? (STDERR)     at require (module.js:380:17)
W20151208-14:12:25.752(-6)? (STDERR)     at Object.<anonymous> (/Users/ncrmro/.meteor/packages/peerlibrary_pdf.js/.1.0.791_4.d8ohlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/canvas/lib/bindings.js:2:18)
W20151208-14:12:25.752(-6)? (STDERR)     at Module._compile (module.js:456:26)
W20151208-14:12:25.752(-6)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151208-14:12:25.752(-6)? (STDERR)     at Module.load (module.js:356:32)
W20151208-14:12:25.752(-6)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151208-14:12:25.752(-6)? (STDERR)     at Module.require (module.js:364:17)
W20151208-14:12:25.752(-6)? (STDERR)     at require (module.js:380:17)
W20151208-14:12:25.752(-6)? (STDERR)     at Object.<anonymous> (/Users/ncrmro/.meteor/packages/peerlibrary_pdf.js/.1.0.791_4.d8ohlj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/canvas/lib/canvas.js:12:14)
W20151208-14:12:25.752(-6)? (STDERR)     at Module._compile (module.js:456:26)
W20151208-14:12:25.752(-6)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151208-14:12:25.752(-6)? (STDERR)     at Module.load (module.js:356:32)
W20151208-14:12:25.752(-6)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151208-14:12:25.752(-6)? (STDERR)     at Module.require (module.js:364:17)
W20151208-14:12:25.752(-6)? (STDERR)     at require (module.js:380:17)
W20151208-14:12:25.752(-6)? (STDERR)     at Object.Npm.require (/Users/ncrmro/Programming/kaasol/.meteor/local/build/programs/server/boot.js:162:18)
W20151208-14:12:25.752(-6)? (STDERR)     at Package (meteor://💻app/packages/peerlibrary_pdf.js/packages/peerlibrary_pdf.js.js:1148:1)
W20151208-14:12:25.753(-6)? (STDERR)     at Package (meteor://💻app/packages/peerlibrary_pdf.js/packages/peerlibrary_pdf.js.js:1406:1)
W20151208-14:12:25.753(-6)? (STDERR)     at /Users/ncrmro/Programming/kaasol/.meteor/local/build/programs/server/packages/peerlibrary_pdf.js.js:1427:4
W20151208-14:12:25.753(-6)? (STDERR)     at /Users/ncrmro/Programming/kaasol/.meteor/local/build/programs/server/packages/peerlibrary_pdf.js.js:1436:3
W20151208-14:12:25.753(-6)? (STDERR)     at /Users/ncrmro/Programming/kaasol/.meteor/local/build/programs/server/boot.js:242:10
W20151208-14:12:25.753(-6)? (STDERR)     at Array.forEach (native)
W20151208-14:12:25.753(-6)? (STDERR)     at Function._.each._.forEach (/Users/ncrmro/.meteor/packages/meteor-tool/.1.1.10.102f3ag++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151208-14:12:25.753(-6)? (STDERR)     at /Users/ncrmro/Programming/kaasol/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

Ubuntu Vagrant

```
W20151208-19:19:33.920(0)? (STDERR)           
W20151208-19:19:33.921(0)? (STDERR) /home/vagrant/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151208-19:19:33.922(0)? (STDERR)                                             throw(ex);
W20151208-19:19:33.922(0)? (STDERR)                                                   ^
W20151208-19:19:34.021(0)? (STDERR) Error: libgif.so.4: cannot open shared object file: No such file or directory
W20151208-19:19:34.022(0)? (STDERR)     at Module.load (module.js:356:32)
W20151208-19:19:34.022(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151208-19:19:34.022(0)? (STDERR)     at Module.require (module.js:364:17)
W20151208-19:19:34.023(0)? (STDERR)     at require (module.js:380:17)
W20151208-19:19:34.023(0)? (STDERR)     at Object.<anonymous> (/home/vagrant/.meteor/packages/peerlibrary_pdf.js/.1.0.791_4.wwmpj1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/canvas/lib/bindings.js:2:18)
W20151208-19:19:34.023(0)? (STDERR)     at Module._compile (module.js:456:26)
W20151208-19:19:34.023(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151208-19:19:34.023(0)? (STDERR)     at Module.load (module.js:356:32)
W20151208-19:19:34.023(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151208-19:19:34.023(0)? (STDERR)     at Module.require (module.js:364:17)
W20151208-19:19:34.023(0)? (STDERR)     at require (module.js:380:17)
W20151208-19:19:34.023(0)? (STDERR)     at Object.<anonymous> (/home/vagrant/.meteor/packages/peerlibrary_pdf.js/.1.0.791_4.wwmpj1++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/canvas/lib/canvas.js:12:14)
W20151208-19:19:34.023(0)? (STDERR)     at Module._compile (module.js:456:26)
W20151208-19:19:34.023(0)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151208-19:19:34.024(0)? (STDERR)     at Module.load (module.js:356:32)
W20151208-19:19:34.024(0)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151208-19:19:34.024(0)? (STDERR)     at Module.require (module.js:364:17)
W20151208-19:19:34.024(0)? (STDERR)     at require (module.js:380:17)
W20151208-19:19:34.024(0)? (STDERR)     at Object.Npm.require (/vagrant/.meteor/local/build/programs/server/boot.js:162:18)
W20151208-19:19:34.024(0)? (STDERR)     at Package (meteor://💻app/packages/peerlibrary_pdf.js/packages/peerlibrary_pdf.js.js:1148:1)
W20151208-19:19:34.024(0)? (STDERR)     at Package (meteor://💻app/packages/peerlibrary_pdf.js/packages/peerlibrary_pdf.js.js:1406:1)
W20151208-19:19:34.024(0)? (STDERR)     at /vagrant/.meteor/local/build/programs/server/packages/peerlibrary_pdf.js.js:1427:4
W20151208-19:19:34.024(0)? (STDERR)     at /vagrant/.meteor/local/build/programs/server/packages/peerlibrary_pdf.js.js:1436:3
W20151208-19:19:34.025(0)? (STDERR)     at /vagrant/.meteor/local/build/programs/server/boot.js:242:10
W20151208-19:19:34.025(0)? (STDERR)     at Array.forEach (native)
W20151208-19:19:34.025(0)? (STDERR)     at Function._.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151208-19:19:34.025(0)? (STDERR)     at /vagrant/.meteor/local/build/programs/server/boot.js:137:5
```

Vagrant Script for Ubuntu

Updated working vagrant provision script.

```
#!/bin/sh

# This script must run with root privileges!
# Vagrant will do this automatically for provisioning.

apt-get -q update
apt-get upgrade

##############################
# Install common packages and useful tools
##############################

apt-get -y install curl imagemagick git python-software-properties

##############################
# Install server side PDF tools
##############################

apt-get -y install libcairo2-dev libfreetype6-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

# Node.js
apt-get -y install nodejs

apt-get -q update

##############################
# Install packages
##############################


# Install the rest with the vagrant user
su vagrant

# Fix resolve problem with git:// URLs
git config --global url."https://".insteadOf git://

# Meteor
curl -silent https://install.meteor.com | /bin/sh
```

**Comment by ncrmro** [comment]
Actually got this working on the vagrant box.

**Comment by mitar** [comment]
Can you describe how you fixed it?

**Comment by mitar** [comment]
Can you describe how you fixed it?

**Comment by ncrmro** [comment]
I fixed this by manually installing the lib gif library's in home-brew/os x.  Downloading the giflib-4.1.6 for os x following the install instructions inside the downloaded folder.

```
Briefly, the shell commands `./configure; make; make install' should
configure, build, and install this package.  The following
more-detailed instructions are generic; see the `README' file for
instructions specific to this package.
```

I've updated the vagrant file provision script above with one the runs correctly.
